### ISSUE TITLE
Consider supporting Covert Encryption

### ISSUE THREAD

**Issue by covert-encryption** [vsajip/pagesign#1]
We are developing an encryption and signing application based on Age, SSH and other popular key formats. It currently provides CLI and GUI written in Python, and we steering the API such that it would be easy to integrate directly also in other applications as a Python module. A C library for bindings to other languages is planned and a Javascript implementation is also already underway to support browsers. Thus, Covert should always be usable without calling external executables.

Have a look at the project page for reasoning on why we made a new format rather than built on Age or others:
https://github.com/covert-encryption/covert

Although it needs to be noted that this project is still in early development, only two months since our initial release.

**Comment by vsajip** [comment]
Thanks for the info, but I'm not sure what support I can give. Actually I've found from my experience with `python-gnupg` that it seems easier to use (and develop with!) the shell-out-to-executable approach than the official Python-bindings-to-C of GPGME, which ultimately still shells out to the executable AFAIK. I wish your project luck, though - new encryption and signing methods need all the help they can get! I prefer to use the existing tools where feasible because I don't want to roll my own cryptography.

**Comment by covert-encryption** [comment]
I appreciate your response.

That generally is the experience you get with most C APIs (I also much rather shell out to openssl to create a certificate and to gpg for encrypting messages than trying to those things via bad C APIs). Ours is a 100 % Python implementation that only uses C via pynacl (for standard crypto primitives) and other libraries, never shelling out to any executable and thus avoiding the use of pipes and temporary files (that may remain on disk after deleted) or potentially calling wrong or missing executables. It should be noted that our Python implementation is already extremely fast and we don't intend to make the Python version use our own C library once done, but to keep it 100 % Python.

I contacted you specifically because your software *already* implements encryption and signing with keystore for PGP and Age/Minisign, in case you might be interested to expand that to Covert once we get to a stable release, likely within about six months from now. Mainly to inform you of the project now, so that it doesn't become as a surprise some time later.

Good luck with your projects as well!

**Comment by vsajip** [comment]
What do you expect to do about the fact that generally people won't trust crypto from most sources they don't know about - is your codebase going to be independently audited, for example?

**Comment by covert-encryption** [comment]
I understand the scepticism when every aspiring coder wants to invent their own crypto, making thirteen bad new cryptography projects a dozen.

We are following a similar development path as Age, and for similar reasons, making cryptography more accessible and more secure than any existing systems could. All kudos to Filippo for making that happen nearly all by himself in the beginning. By standing on their shoulders and by having more developers we have been able to make very rapid progress.

The Covert format is designed by me in cooperation with someone far more knowledgeable in cryptography, and is based on earlier work by us and by others (Age being a great inspiration). [PURB](https://petsymposium.org/2019/files/papers/issue4/popets-2019-0056.pdf) was not known to us when we designed the principles but it is interesting to see that the most popular paper on this field ended up with a very similar design to ours.

So far we have gained valuable reviews from a world class cryptographer as well as other outsiders in particular thanks to a [/r/crypto post](https://www.reddit.com/r/crypto/comments/rbf7iw/covert_encryption/). Although I did not see Age being audited yet, an audit is in order for us when we reach stable. Since we don't invent any new cryptography, we don't intend to publish any research papers.

**Comment by vsajip** [comment]
That's good information to know - thanks. It'll be interesting to see how things shape up as these new tools get wider adoption. In my own little way, this project is an attempt to encourage things - perhaps some users of `python-gnupg` will find it easier to switch to newer approaches if this library, which follows a similar approach, can work for them. The whole issue of key distribution is still a thorny issue, though, isn't it?

**Comment by covert-encryption** [comment]
Indeed, keys are always the biggest issue. We currently (optionally) bundle sender pk with messages so that the other party can reply. This could be at some point be replaced by a ratchet following Signal protocols such the message keys are generated on a chain and disposed whenever messages are received (forward secrecy) and so that the chain is ECDH-renegotiated whenever a message round-trip is done (backward secrecy). That can work quite transparently to users, as all the exchange happens in message headers and with currently active temporary keys stored locally in each user's id-file. When Alice sends a message to Bob, she doesn't even need to have a key pair, as a temporary pseudonymous key can be created (Bob will know that he talks with the same person as before in the same conversation, but not who that person is).

Still, the initial message remains a problem. Alice will need Bob's public key to send him a message in the first place  Maybe Alice can find it via `github:bob` (which unfortunately rarely works even for developers). But then the initial message that Alice sends can always and forever be decrypted with that key. No forward secrecy.

Signal's X3DH (another protocol unrelated to the double ratchet) solves this problem but requires keys that actually contain multiple keys. A permanent identity key (like your typical PGP key), a short-term key (frequently replaced to provide some forward and backward secrecy), and ideally also a one time key (perfect forward secrecy). The short term key is signed with the permanent key, so that that everyone knows they are from Bob and not Malice. One time keys require that Bob creates a batch, say 1000 keys, sending them all to a keyserver, which dispenses one of them to each user who requests Bob's key. If the one time keys run out, X3DH falls back to short term keys. I suppose Bob could run his own keyserver that just creates one time keys on demand, as they are not signed. The session keys depend on all three keys as well as sender's id key and the message ephemeral key, so a fake one time key doesn't allow Mallory to join in.

Still, I believe not even the keyserver part has really been solved in an open system. But in principle Alice has to learn from *somewhere* that Bob exists, and learn his account name, telephone number or (yuck) email, whatever to even send the message. So, it would be sensible if the key could always be acquired from the same place. This can certainly work with short term keys, provided that Bob frequently updates the info, and if there was a link to the keyserver, even one time keys could work. Or a step more, and you've Signal (or any other cryptomessenger, there certainly are plenty of them to choose of).

And then there still is the trust issue. Who knows that NSA did't hack Bob's Twitter to show fake contact info and fake keys to Alice? Well, that's a discussion I am definitely not getting into.

Initial key distribution is not our loaf of bread, our hands are full with the encryption itself, but just some food for thought.

**Comment by vsajip** [comment]
> Initial key distribution is not our loaf of bread

Indeed :rofl:
